### PR TITLE
Documentation & Migration Guide

### PR DESCRIPTION
**Pull request by MarkPieszak**
###  Work in progress

- [X] Summary of how Universal works
- [x] What is Preboot?
- [x] Benefits of Universal
- [x] Example application (main files)
   - [ ] Update to latest rc6 changes & new platform
- [ ] Explain how Universal is setup
  - [ ] UniversalModule
  - [x] NodePlatform
  - [ ] UniversalPlatform
- [ ] Showcase integrations
   - [ ] express-engine
   - [ ] webpack-prerender
   - [ ] hapi-engine
   - [ ] gulp-prerender  
   - [ ] grunt-prerender
- [x] Migration guide 
   - [ ] Show what has changed & why (things due to NgModule etc)
   - [X] Show ExpressEngineConfig vs Now: `NodeModule.withConfig( )`
   - [ ] Showcase what's inside the `NodeModule.withConfig({ /* ?? */ })` object

### CODE REVIEW

**Comment by gdi2290** [comment]
looks great so far keep it up 👍

**Comment by jonathan-casarrubias** [comment]
Great effort!! thank you @MarkPieszak

**Comment by devCrossNet** [comment]
@jeffwhelpley told me to name the entry points start-browser.ts and start-node.ts. This is what I took for the CLI integration. Is this still valid?

**Comment by gdi2290** [comment]
merging for now

**Pull request merged**
