### PR TITLE
feat(engines): add optional url and document to render options

### PR DESCRIPTION
**Pull request by gdi2290**
* Add url and document as optional parameters for rendering
* Add optional parameters setup to the README

### CODE REVIEW

**Comment by Toxicable** [comment]
Same error we're getting here https://github.com/angular/universal/pull/808#issuecomment-333015738

Maybe update docs to show you can optionally use those thsoe now?
Also might ben nice to update Hapi to have the same API to try be consistant

**Comment by vikerman** [comment]
Yes - Can you update the other engines with similar options and update the README?

**Comment by CaerusKaru** [comment]
@gdi2290 Are you still tending to this PR? If not, I can add the changes and push to this branch.

**Comment by gdi2290** [comment]
@CaerusKaru you can take this PR over

**Comment by CaerusKaru** [comment]
@vikerman This is ready for review again. @MarkPieszak can you take a look as well?

**Comment by MarkPieszak** [comment]
LGTM, i'll test it out in the webpack & CLI dotnet apps when it lands as well to double check.

**Comment by sjogren** [comment]
Very nice! We are dependent on this feature in our current project. Does anyone know when this will be available on npm?

**Pull request merged**
