### PR TITLE
build(builders): update browser-sync to remove engine.io security issues

### PR DESCRIPTION
**Pull request by yharaskrik**
Updates `browser-sync` to newest version which in tern updates `socket.io` to v4 and will update `engine.io` to remove security vulnerability issues when using Angular Universal SSR.

image

### CODE REVIEW

**Comment by alan-agius4** [comment]
This change should not be necessary, please update your lock file.

**Comment by yharaskrik** [comment]
Update what packages? My Angular and NgUniversal packages are all up to date (Angular is on newest 14 and nguniversal is on 14.2.0) is there another package i need to update somewhere? My lock file seems to be up to date from what i can tell (even removed it and ran `yarn --check-files`)

**Comment by alan-agius4** [comment]
`^2.26.7` does satisfy `^2.27.10` see https://semver.npmjs.com/
Screenshot 2022-10-13 at 12 26 53


@yharaskrik, did you run the below to re-generate the lock file?

```
rm -rf node_modules yarn.lock
yarn install
```

Post the above run
```
yarn why browser-sync
```

**Comment by alan-agius4** [comment]
For some additional context, this vulnerability does not effect Angular SSR as the dev-server should not be used on production environments.

**Comment by alan-agius4** [comment]
Closing as per above.

**Pull request closed without merging**
