### PR TITLE
feat(demo): add falcor demo

### PR DESCRIPTION
**Pull request by wesleycho**
- Add basic falcor demo

This is towards addressing #86 - this is still a WIP essentially, but safe as is.

### CODE REVIEW

**Comment by gdi2290** [comment]
can you use the same server?

**Comment by wesleycho** [comment]
Yep - did a refactor

**Comment by gdi2290** [comment]
We should mock out the api rather than including the lib but for now let's just get it in

**Comment by wesleycho** [comment]
Wait...what github?

**Comment by wesleycho** [comment]
Ah I see...confusing history

**Comment by gdi2290** [comment]
merged via https://github.com/angular/universal/commit/36f2dcae6bdeaf3b2e77048f3126c839bf960f28

**Pull request closed without merging**
