### PR TITLE
fix Parse5 adapter

### PR DESCRIPTION
**Pull request by gdi2290**
correctly use parse5 options to fix innerHtml problem
fixes https://github.com/angular/universal/issues/558 https://github.com/angular/universal/pull/556

### CODE REVIEW

**Comment by jeffbcross** [comment]
Why do we not have type information for parse5?

**Comment by jeffwhelpley** [comment]
Ah...scratch my comment about not seeing ngJeff's comments. I am just getting used to the new GitHub code review feature.

**Comment by MarkPieszak** [comment]
@jeffbcross parse5 doesn't include any type definition files unfortunately :(

@gdi2290 This fixed the innerHTML issue? Feel like the other week I tried  `{ treeAdapter: parse5.treeAdapters.htmlparse2 }` but it didn't work for me. Guess this renders differently?

**Comment by jeffbcross** [comment]
There are definitions at @types/parse5 (though I don't know if they're high-quality).

**Comment by MarkPieszak** [comment]
Wow you're right those must be very new looks like they're based off of 2.*+ as well! That's great news.

     // Type definitions for parse5 2.2.0

Good find :+1:

**Comment by fabiotisci** [comment]
Hi guys, any news about this? Any chance somebody merge those conflicts 🎱

**Comment by jeffwhelpley** [comment]
@gdi2290 what were follow up items on this PR from our meeting?

**Comment by MarkPieszak** [comment]
Think to upgrade parse5 with the latest from Core (that last commit I made, not sure why google bots complaining) and test it out make sure it fixes innerHTML etc @jeffwhelpley

**Comment by scott-wyatt** [comment]
Is there anything the community can do to speed this PR up? I'm really looking forward to this fix :-)

**Comment by MarkPieszak** [comment]
We spent a few hours looking into it last night, and there were a few other features added in there. Hopefully we'll get the PR sorted out asap! @scott-wyatt

**Comment by scott-wyatt** [comment]
I really appreciate your efforts! I would also love to see a label or something that can mark issues that you want the community to solve. I would love to help, as my company is going to make universal our go to strategy.

**Comment by gdi2290** [comment]
closing for https://github.com/angular/universal/pull/590

**Pull request closed without merging**
