### PR TITLE
fix(hapi-engine): update hapi-engine integration

### PR DESCRIPTION
**Pull request by bisubus**
- **What modules are related to this pull-request**
- [ ] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [x] hapi-engine
- [ ] universal-next
- [ ] universal
- [ ] webpack-prerender
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
  remove unused proxy imports from some test files

Adds the implementation of Hapi template view engine for Universal, similar to Express engine.
- **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
  No

### CODE REVIEW

**Comment by MarkPieszak** [comment]
@bisubus Let us know if you need any help with how the express engine is doing things. Shouldn't be too bad though.

**Comment by bisubus** [comment]
@MarkPieszak Thanks, I guess I've sorted this out, rendering part is quite straightforward.

**Comment by bisubus** [comment]
That's ok, googlebot.

**Comment by yannickglt** [comment]
Need this! 👍

**Comment by gdi2290** [comment]
won't be added in ng4 
https://github.com/angular/angular/issues/13822

**Pull request closed without merging**
