### PR TITLE
module(server): Create Node version for Router #60

### PR DESCRIPTION
**Pull request by manekinekko**
PR for task #60 

@gdi2290 what do you think?

### CODE REVIEW

**Comment by gdi2290** [comment]
LGTM
merging

**Comment by manekinekko** [comment]
thanks. and sorry again for the multiple PRs.

**Comment by gdi2290** [comment]
merged, no worries about the PRs. It's a lot easier making another one than trying to fix the current one sometimes

**Comment by manekinekko** [comment]
As you see, I still need to master the git squash command :smile:

**Comment by gdi2290** [comment]
tbh I ended up using the github GUI https://desktop.github.com/ if only for the code diffs and the undo button

**Pull request merged**
