### PR TITLE
fix(package.json): fix repository main urls

### PR DESCRIPTION
**Pull request by tamascsaba**
Main URL was wrong.
New files are compiled to ```dist``` not ```dist/universal``` with ```tsc || true```.
In ```tsconfig.json```

```
"compilerOptions": {
    ...
    "outDir": "dist"
  },
```

### CODE REVIEW

**Comment by dbabaioff** [comment]
After installing using npm (v0.20) I have this **dist** folder:
```
.
├── client
│   └── src
├── preboot
│   └── src
│       ├── interfaces
│       └── server
├── server
│   ├── src
│   │   ├── directives
│   │   ├── express
│   │   ├── http
│   │   ├── platform
│   │   ├── render
│   │   └── router
│   └── test
└── universal
    ├── client
    │   └── src
    └── server
        ├── src
        │   ├── directives
        │   ├── express
        │   ├── http
        │   ├── platform
        │   ├── render
        │   └── router
        └── test

```
 then, I removed the dist folder and ran:
```
tsc
```

And this is the **dist** folder after **rm -rf dist** and **tsc**:
```
.
├── client
│   └── src
└── server
    ├── src
    │   ├── directives
    │   ├── express
    │   ├── http
    │   ├── platform
    │   ├── render
    │   └── router
    └── test
```

**Comment by tamascsaba** [comment]
@dbabaioff :+1: in universal folder are outdated code, i don't understand where come from.

**Comment by gdi2290** [comment]
thanks!

**Comment by gdi2290** [comment]
screen shot 2016-01-06 at 9 53 46 pm
via https://github.com/angular/universal/commit/08538ea940f396ebbfecfdce541f712ff3666d3c

**Pull request closed without merging**
