### PR TITLE
fix(@nguniversal/express-engine): update import for template server file

### PR DESCRIPTION
**Pull request by brandonroberts**
The `server.ts` is missing a single tick on the import

### CODE REVIEW

**Review by alan-agius4 — COMMENTED** [review]
Can you please update the commit message to `fix(@nguniversal/express-engine): …`?

**Comment by brandonroberts** [comment]
Yep, done

**Comment by alan-agius4** [comment]
> Yep, done

The scope is still incorrect.

**Comment by alan-agius4** [comment]
Looks like you need to update the unit test 

https://github.com/angular/universal/blob/7b767d2c1514066fee7a77e5a241b92fcd035045/modules/express-engine/schematics/install/index.spec.ts#L112

**Review by alan-agius4 — APPROVED** [review]
LGTM, thanks

**Pull request merged**
