### PR TITLE
Added caching for POST requests. Fixed bug for caching GET requests w…

### PR DESCRIPTION
**Pull request by vytautas-pranskunas-**
…ith params.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
```
[X] Bugfix
[X] Feature
```

## What is the current behavior?
POST requests are not cached so flickering appears when using pure JSON API
Get requests cache does not respect request params

## What is the new behavior?
It should cache POST requests
Fixed bug when GET requests with different params are cached:
https://github.com/angular/universal/issues/927

## Does this PR introduce a breaking change?
```
[X] Yes
[ ] No
```

.forRoot() method should be called

## Other information

### CODE REVIEW

**Comment by Toxicable** [comment]
Sorry but we're not going to merge the POST caching part.

However we'd be happy to put int the params part, that's a good feature to have put in.

**Comment by vytautas-pranskunas-** [comment]
Why POST caching is not good? Because hen Ssr is only for REST api :(

**Comment by patrickmichalina** [comment]
Generally POST requests are consider non-cacheable. It would be nice to allow a DI config value to support this though.

**Comment by vytautas-pranskunas-** [comment]
Would it be ok if i add it to foroot call?

**Comment by Toxicable** [comment]
@vytautas-pranskunas- No we cant take a forRoot sorry, it'll be too easy for users to accidentally enable.

While almost any of the HTTP verbs can be used however you like we prefer to stick to what they semantically mean. 
There's an issue here on the topic: https://github.com/angular/universal/issues/855

**Comment by vytautas-pranskunas-** [comment]
I do not see how they can turn it by accident. i do not see any issue with cachable POST also because during ssr app_initializer, canActivate and similar calls are executed and those are not data changing requests they are like getters just in pure Json style. But probably you are right and we never know what can happen.  So i can add to forRoot call array of routes that should be cachable by POST. How does that sounds? Otherwise that's huge limitation of ssr because we cannot have it with pure Json api.

**Comment by Toxicable** [comment]
@vytautas-pranskunas- That's my point. In your example your POST requests do not mutate the data, therefore they do not invalidate the already cached data.
Which is fine, as I mentioned above you can use the HTTP verbs however you like. 
But POST is intended to mutate data, not to retrieve it and that's the definition we're going to take on this.

We are happy to take the params part only, if you refactor it to just be that then I'll review it from there.

You're welcome to re-implement this in your own lib if you really need it that much, but for the general case we must remain consistent for everyone using it. Allowing POST to be cached would break a lot of apps without people knowing it.

**Comment by vytautas-pranskunas-** [comment]
Hi,

should i make new pull request?
I have added to forRoot options obejct where you have to define POST request filter. SO by default POST caching is disabled but you can allow it and add different checks for example: allow caching for certain urls or any other. 
I think this would give pure JSOn api users ability to use SSR without braking anything accidenlty.

**Comment by Toxicable** [comment]
A new pull request just for the Params caching would be good

**Comment by vytautas-pranskunas-** [comment]
But i refactored whole POST request system. Or you saying that whole world should stic to REST Api if they want to use SSR? So you need to mention it before people pick framework. I think you are wrong and we all should look the best way to allow limitted POST caching.

**Comment by EreckGordon** [comment]
What kind of post requests would be a good idea to cache? I'm drawing a blank.

**Comment by vytautas-pranskunas-** [comment]
Non changing POST requests. Same as GET's. It is only a matter of protocol and approach people use. REST or JSON-Pure

**Pull request closed without merging**
