### PR TITLE
chore(build): upgrade most npm scripts to gulp tasks

### PR DESCRIPTION
**Pull request by manekinekko**
PR for task https://github.com/angular/universal/issues/42.

Here are the tasks I added in *scripts/gulp-tasks/*.: 
- **build**
- **build.preboot**
- **build.typescript**
- **serve**
- **watch**
- **debug**
- **clean**
- **karma**
- **changelog** 
- **protractor** 
- **protractor.start**
- **protractor.update**
- **protractor**

Please note these gulp tasks are based on the **batter** module API.

In the *package.json* file I left the script command, but most of them are just aliases to gulp tasks (for backward compatibility):

```json
"prestart": "gulp build",
"build": "gulp build.typescript",
"serve": "gulp serve",
"start": "gulp serve",
"watch": "gulp watch",
"debug": "gulp debug",
"clean": "gulp clean",
"preboot": "gulp build.preboot",
"test": "gulp karma",
"changelog": "gulp changelog",
"e2e": "gulp protractor",
"webdriver-update": "gulp protractor.update",
"webdriver-start": "gulp protractor.start",
"preprotractor": "gulp protractor.update",
"protractor": "gulp protractor",
````

The following commands were not migrated to gulp because they run git commands or shell scripts. 
But this is fine, they are executed during *npm install* lifecycle anyway.

```json
"remove-angular2": "...",
"remove-angular-typings": "...",
"update-angular": "...",
"pull-angular": "...",
"angular-submodule": "...",
"bower": "...",
"web_modules": "...",
"tsd": "...",
"preinstall": "...",
"postinstall": "..."
```

Enjoy!

### CODE REVIEW

**Comment by manekinekko** [comment]
@gdi2290 I included the specific commit of angularjs (450d363) in order to match the one in your master. But still, github can not auto merge. I don't know what to do more. Any hint?

**Comment by manekinekko** [comment]
@gdi2290 If you still can not merge this PR let me know so I can send you by email the updated files, so you can apply them using the old way (copy/paste) :wink:

**Comment by gdi2290** [comment]
@manekinekko I was rebasing the commit and found out the problem. The state of your branch was made after this commit https://github.com/angular/universal/commit/17bf16a072a6d4c774bb2b59234db0e0ff84eefc so when I do a rebase I have to rewrite history where it conflicts. This means other commits you made were affected by it. Can we jump on google hangout or screenhero? We just need to update the feature branch with latest changes before adding your changes on top of it

**Comment by manekinekko** [comment]
@gdi2290 I was working in this issue this afternoon, I was obsessed with this whole merge thing.
So I think I found the root as well. My branch master was not sync with your master branch. I had no `upstream`. 

I've sent you another PR https://github.com/angular/universal/pull/58  (I hope the last one). It seems to merge well. Tell me if it is OK.

**Pull request closed without merging**
