### PR TITLE
chore(universal): rename "client" to "browser"

### PR DESCRIPTION
**Pull request by manekinekko**
...and fix https://github.com/angular/universal/issues/216

### CODE REVIEW

**Comment by gdi2290** [comment]
@manekinekko can you rebase

**Comment by manekinekko** [comment]
I just crossed my fingers and hit rebase :8ball:

**Comment by gdi2290** [comment]
@manekinekko did you run `git pull --rebase upstream master`? it seems like you did a merge commit

**Comment by manekinekko** [comment]
Yeah, I run this command, and then I had to resolve two conflicts, followed
by a push.
I may then have done rebasing my branch onto master hence the merging and
the commit.


Wassim Chegham
Expert Nouvelles Technologies Web
Google Developer Expert
<http://fr.linkedin.com/in/wassimchegham>  <http://twitter.com/manekinekko>
<http://plus.google.com/+WassimCheghamJavaScript/posts>
<http://flickr.com/photos/manekinekko/albums/>
<http://github.com/manekinekko>  <http://wassimchegham.com/feed>
<http://wassimchegham.com/>  <http://www.meetup.com/members/135357292/>
<http://slides.com/wassimchegham/>

**Comment by gdi2290** [comment]
@manekinekko when you get a merge conflict you can fix it then run `git add . && git rebase --continue` but ya I think you might have rebased origin. you can also run `subl .git/config` to see what the current branches are pointing to

**Comment by manekinekko** [comment]
@gdi2290 how can I easily revert to normal and try another rebase?

**Comment by manekinekko** [comment]
Here is a new PR https://github.com/angular/universal/pull/225 trying to fix this PR :)

**Comment by gdi2290** [comment]
merged via https://github.com/angular/universal/pull/225

**Pull request closed without merging**
