### PR TITLE
fixed "git submodule update" issue when pulling angular2.

### PR DESCRIPTION
**Pull request by manekinekko**
fixing issue https://github.com/angular/universal/issues/38

### CODE REVIEW

**Comment by gdi2290** [comment]
thanks! LGTM, merging

**Comment by gdi2290** [comment]
I had to rewrite your commit message.
merged via https://github.com/angular/universal/commit/40f798661903d1673eb88a953d0ddec601ab99dd

**Comment by manekinekko** [comment]
OK. Is the prefix "chore(build):" mandatory? Is there a pattern I should follow for my next commits?

**Comment by gdi2290** [comment]
yeah the idea is following the angular contrib guide although I'm not really generating a changelog yet
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines

**Comment by manekinekko** [comment]
Thx.

BTW, I am having various issues with the build process. Do you recommend:
1) opening one GH issue per problem 
2) one GH issue for all problems related to the build process

**Comment by gdi2290** [comment]
yeah can you open one issue since this is a build step problem

**Comment by manekinekko** [comment]
Sure. I will do that.

**Pull request closed without merging**
