### PR TITLE
upgrade npm scripts to a task manager

### PR DESCRIPTION
**Pull request by manekinekko**
PR for https://github.com/angular/universal/issues/42. As usual, only last commit https://github.com/angular/universal/commit/3a45d9f400ce3af8e3a1b1f4afaed02cdba5d203 matters. I really need to figure out how to isolate specific commits that should be sent to PR.

### CODE REVIEW

**Comment by gdi2290** [comment]
can you rebase?

I think the problem is that you need to update your master branch before creating a branch otherwise you would have to do a git rebase

**Comment by manekinekko** [comment]
let me try that.

**Comment by manekinekko** [comment]
Hmmm. I already rebase my feature branch on master. I can see all commits that were moved to master.
I am sorry about that. I am kinda new to the rebase command :crying_cat_face: 

Should I delete this feature branch and start over?

**Comment by gdi2290** [comment]
no worries, the only way to truly learn git is by messing up and finding ways to fix it. It's easier if you open  only the files you changed then `git checkout` to `master`. Ensure you're local `master` branch are showing the latest changes in git history then create a branch and save the files

**Comment by manekinekko** [comment]
LOL! I am doomed. It just keeps adding commits to master branch what ever I do :weary: 
I even tried to reset all my changes but no way. I am thinking of deleting my fork and create another one.  Sounds radical?

The thing is that master already contains the update I want to PR. I think I might have merged my feature branch onto master. I think I'll stop working with branches when doing PRs :wink:

**Comment by gdi2290** [comment]
haha this is why --force was created. you might be able to force pull to replace your master branch

**Comment by manekinekko** [comment]
YOHOO! I think I am almost there.

**Comment by manekinekko** [comment]
Here sir: https://github.com/angular/universal/pull/53

**Pull request closed without merging**
