### PR TITLE
docs(readme): best practices for components

### PR DESCRIPTION
**Pull request by gdi2290**
Best practices for components as bullet points

related https://github.com/angular/universal/issues/124

### CODE REVIEW

**Comment by zhaxi** [comment]
@gdi2290 could universal component be webworker component at same time? I see angular2 & universal export different bootstrap, could one codebase both support universal app and webworker app? I feel a little confused.

**Comment by gdi2290** [comment]
So a Universal component can work on the Client/Server/Webworker hence the term universal. I can show an example of a Universal Angular 2 app that is server rendered then loaded on the Client within a WebWorker if you like.

**Comment by zhaxi** [comment]
I'd like to see your example! And I have another related question, If I want to support android 4.4-(without webworker support) and android4.4+(with webworker support), It's seems to me that we need two sets of code, With Universal Component&other help, could it be possible that we only need one set of codes(just like view encapsulation in NG2 native&emulated) to ensure compatibiity&best performance, thanks!

**Comment by zhaxi** [comment]
@gdi2290 when can I see your example?

**Pull request merged**
