### PR TITLE
fix(aspnet): remove duplicate options providers registration

### PR DESCRIPTION
**Pull request by stephenlautier**
* **Please check if the PR fulfills these requirements**
```
- [x] The commit message follows our guidelines: https://github.com/angular/universal/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
```

* **What modules are related to this pull-request**
```
- [x] aspnetcore-engine
- [ ] express-engine
- [ ] hapi-engine
```

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Fix

* **What is the current behavior?** (You can also link to an open issue here)
Options providers are registered as duplicates

* **What is the new behavior (if this is a feature change)?**
Removed duplicates option providers

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Other information**:

### CODE REVIEW

**Comment by stephenlautier** [comment]
@CaerusKaru merged - ready to be merged

**Comment by MarkPieszak** [comment]
How can someone pass in providers without this? 

Also maybe this one be closed with the previous PR?

**Comment by CaerusKaru** [comment]
@MarkPieszak The options.providers are _concatenated_ with the new providers, which is why they’re duplicated.

**Comment by stephenlautier** [comment]
@MarkPieszak @CaerusKaru yes now this is redundant as I had opened this before the other and I had made the changes with the other as well. So this can be closed off.

**Pull request closed without merging**
