### PR TITLE
feat(common): introduce common engine

### LINKED ISSUE #726: Create a common universal module
* **I'm submitting a ...**
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
Currently there is some code duplication across the ASP.Net and Express engines, and the in-progress Hapi engine. This creates risk of code divergence due to code duplication.

* **What is the expected behavior?**
I expect there to be a common module for imports so that the common code becomes easier to manage.

* **What is the motivation / use case for changing the behavior?**
Reduced burden of maintainability

### LINKED ISSUE #790: proposal: @nguniversal/core package
* **I'm submitting a ...**
```
- [x] feature request
```
For features like 
- StateTransfer
- Interceptor for HttpClient #766
- localStorage replacement
- Document Service (Title/Meta)
- lsRoutes
- module-map-ngfactory-loader
- Other common functions and utilities for Universal Engine Implimentations

I propose that they should all be grouped under `@nguniversal/core`
While a lot of those features are more "utility" functions I think grouping them under core is still a reasonable solution since they are will not be grouped/provided by an NgModule therefore they should all still be tree shakable.
Otherwise once we start implementing some of these features we're going to have a very long list of packages to be published from this Repo, since none of them fit in with the current modules we're currently publishing from here
With this implemented it will be easier to add new features and distribute them.

To reaffirm the goal of this is to only have 2 types of packages published from this repo: 
`@nguniversal/core`
`@nguniversal/(platform)-engine`

related issues: #726 , 
related PR: #780

### PR DESCRIPTION
**Pull request by Toxicable**
* **Please check if the PR fulfills these requirements**
```
- [x] The commit message follows our guidelines: 
- [x] Tests for the changes have been added (for bug fixes / features)
- [] Docs have been added / updated (for bug fixes / features)
```

* **What modules are related to this pull-request**
```
- [x] Core
```

* **What is the current behavior?** (You can also link to an open issue here)
There is no code sharing between engines
closes #726
closes #790

* **What is the new behavior (if this is a feature change)?**
A new module for sharing platform unspecific code
Introduce `UniversalEngine` for sharing engine code
Implement `UniversalEngine` in Express and Hapi Engine

### CODE REVIEW

**Comment by MarkPieszak** [comment]
This is great, we actually meant to get do this a while ago! Nice 👍

**Comment by Toxicable** [comment]
@MarkPieszak I wasn't sure if this package should be published so i've added in the package.json to indicate dependencies but i've done relative links from the other Engines to the Core module

**Comment by MarkPieszak** [comment]
Yeah we probably don't need to need to publish it. Yeah the other libraries can just reference & use some of these files if needed. Having a Core place for shared code was definitely needed though!

**Comment by Toxicable** [comment]
@MarkPieszak Cool well I think it's good to go now, there's a few other things from the aspnetcore engine that could be extracted but might wait till that's a bit more standard

**Comment by MarkPieszak** [comment]
Yeah I need to make a few tweaks to that as well, hopefully in the next few days. Finally have a little time to upgrade the .net repo as well.

**Comment by Toxicable** [comment]
After looking through at what features might be next in the pipeline I think that this should actually be a published module as per the reasoning here #790

**Comment by Toxicable** [comment]
I've made a few changes here:
- used the `ɵ` symbol to indicate API's private to the repo
- added `@nguniversal/core` as a peerDependancy for other modules

This will help moving forward with introducing new features

**Comment by Toxicable** [comment]
@vikerman Could you review this?
Would like to have this merged before implementing other features

**Comment by Toxicable** [comment]
I "think" this is good to go now, it's hard to be certain without testing.
Would also like to use the new `UniversalEngine` in the aspnetcore Engine but I think that might have to be up to @MarkPieszak

**Comment by Toxicable** [comment]
Waiting on putting in some testing so we can make this change knowing that we havn't broken anything

**Comment by Toxicable** [comment]
Superseed by https://github.com/angular/universal/pull/912

**Pull request closed without merging**
