### PR TITLE
feat(socket-engine): add providers parameter

### PR DESCRIPTION
**Pull request by someApprentice**

### CODE REVIEW

**Comment by CaerusKaru** [comment]
Please sign the CLA, fix the build errors, and add a small unit test. Other than that, great work!

**Comment by someApprentice** [comment]
> Please sign the CLA, fix the build errors, and add a small unit test. Other than that, great work!

Affirmative! I will do that tomorrow, since time in my timezone is quite late.

**Comment by someApprentice** [comment]
@CaerusKaru 

Im pretty new at JavaScript and Angular itself and I have some issues with a building application.

After `npm install` and `/universal$ bazel build -- :all` I did `bazel run @yarn//:yarn` and `/universal$ ./scripts/build-modules-dist.sh` as it was on CircleCI, and I got this error:

```
ERROR: /universal/modules/common/BUILD.bazel:19:1: ng_package: Rollup //modules/common:npm_package failed (Exit 1)
[!] Error: 'RenderOptions' is not exported by ../../../../../execroot/nguniversal/bazel-out/k8-fastbuild/bin/modules/common/npm_package.es6/modules/common/engine/src/index.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
../../../../../execroot/nguniversal/bazel-out/k8-fastbuild/bin/modules/common/npm_package.es6/modules/common/engine/private_api.js (12:67)
```

Followed by [suggested link](https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module) I checked these files and as expected I didn't found exported `RenderOptions` in `...src/index.js`:

```
export { } from "./interfaces";
```

`...src/interfaces.js:`
```
export function RenderOptions() { }
function RenderOptions_tsickle_Closure_declarations() {
    /** @type {?} */
    RenderOptions.prototype.bootstrap;
    /** @type {?|undefined} */
    RenderOptions.prototype.providers;
    /** @type {?|undefined} */
    RenderOptions.prototype.url;
    /** @type {?|undefined} */
    RenderOptions.prototype.document;
    /** @type {?|undefined} */
    RenderOptions.prototype.documentFilePath;
}
```

Can you give some tips what am I doing wrong? Should I simple add this dependency to the `export`?

**Comment by someApprentice** [comment]
> Can you give some tips what am I doing wrong? Should I simple add this dependency to the `export`?

I fixed this issue simple removed `RenderOptions as ɵRenderOptions` dependency from **`universal/modules/common/engine/private_api.ts`**, rebuild application (got error about lacking interface), returned this dependency back and rebuild application again. That time error didn't happen. Not sure what caused that behavior at the first time. Hope that helps someone in the future.

**Comment by someApprentice** [comment]
>ci/circleci: integration_test — Your tests failed on CircleCI 
>
>error "/home/circleci/ng/node_modules/@angular/animations" doesn't exist.

Not sure what causing that error on CircleCi. On my local machine the test is passed. Please check out your CircleCi environment and give me admonition if I thought made a mistake.

```
universal$ ./integration/run_tests.sh
##################################
scripts/build-modules-dist.sh:
  building @nguniversal/* npm packages
##################################
WARNING: Switched off --watchfs again... temporarily falling back to manually checking files for changes
INFO: Analysed 7 targets (0 packages loaded).
INFO: Found 7 targets...
INFO: Elapsed time: 5.176s, Critical Path: 0.57s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
# Copy artifacts to /home/user/Downloads/universal/scripts/../dist/modules-dist/aspnetcore-engine
# Copy artifacts to /home/user/Downloads/universal/scripts/../dist/modules-dist/common
# Copy artifacts to /home/user/Downloads/universal/scripts/../dist/modules-dist/express-engine
# Copy artifacts to /home/user/Downloads/universal/scripts/../dist/modules-dist/hapi-engine
# Copy artifacts to /home/user/Downloads/universal/scripts/../dist/modules-dist/module-map-ngfactory-loader
# Copy artifacts to /home/user/Downloads/universal/scripts/../dist/modules-dist/socket-engine
#################################
Running integration test common
#################################
yarn install v1.10.1
info No lockfile found.
[1/4] Resolving packages...
warning babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
$ webdriver-manager update --gecko false --standalone false $CHROMEDRIVER_VERSION_ARG
[19:27:07] I/file_manager - creating folder /home/user/Downloads/universal/integration/common/node_modules/webdriver-manager/selenium
[19:27:07] I/config_source - curl -o/home/user/Downloads/universal/integration/common/node_modules/webdriver-manager/selenium/chrome-response.xml https://chromedriver.storage.googleapis.com/
[19:27:09] I/downloader - curl -o/home/user/Downloads/universal/integration/common/node_modules/webdriver-manager/selenium/chromedriver_2.42.zip https://chromedriver.storage.googleapis.com/2.42/chromedriver_linux64.zip
[19:27:10] I/update - chromedriver: unzipping chromedriver_2.42.zip
[19:27:10] I/update - chromedriver: setting permissions to 0755 for /home/user/Downloads/universal/integration/common/node_modules/webdriver-manager/selenium/chromedriver_2.42
Done in 69.82s.

...
```

**Comment by CaerusKaru** [comment]
The integration test job can be pretty flaky. I’ve been meaning to fix it, but in the meantime I’ve restarted the job (which usually works).

**Comment by CaerusKaru** [comment]
@someApprentice Thank you again for putting this together, you did a great job!

**Pull request merged**
