### PR TITLE
fix(express-engine): add bundleDependencies and lazy-loading fixes

### PR DESCRIPTION
**Pull request by CaerusKaru**

### CODE REVIEW

**Comment by vikerman** [comment]
Fixes https://github.com/angular/angular-cli/issues/12273 !!

**Comment by vikerman** [comment]
Fixes https://github.com/angular/angular-cli/issues/8616

**Comment by MarkPieszak** [comment]
Wow !! I didn't know you guys were working on this - do you need me to look into anything / test it with some aspnet core apps? Amazing 👏

**Comment by vikerman** [comment]
@MarkPieszak - We are essentially moving anything @angular or @nguniversal related to main.server.ts so that we don't end up with two copies of Angular.

How does this affect ast.net setup?

**Pull request merged**
