### PR TITLE
Fixes "str.replace is not a function" when passing custom object

### PR DESCRIPTION
**Pull request by jimmythesaint82**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/universal/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What modules are related to this pull-request**
- [ ] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [ ] hapi-engine
- [ ] universal-preview
- [X] universal
- [ ] webpack-prerender

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
remove unused proxy imports from some test files
Bug fix

* **What is the current behavior?** (You can also link to an open issue here)
Crash with str.replace not found on passing a custom object into the node_dom_renderer

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Other information**:

### CODE REVIEW

**Comment by jimmythesaint82** [comment]
I signed it

**Comment by visikov** [comment]
This should also account for `typeof number`, fyi.

**Comment by MarkPieszak** [comment]
Looks good to me again, I'll leave it to let Patrick take a look and merge it.

What is all the change log stuff? @jimmythesaint82

**Comment by jimmythesaint82** [comment]
Change log was an accidental commit, remove it

**Comment by visikov** [comment]
One thing that should really be discussed is whether or not printing objects into the document is a good idea.

Some tests should be made to check if this could result in invalid html.

**Comment by jimmythesaint82** [comment]
It does not at present but is possible. This has been tested on two
separate projects and seems to go fine. But some other testing could be
done.

**Comment by gdi2290** [comment]
thanks!

**Pull request merged**
