### PR TITLE
build: change rm -rf to rimraf to prevent npm install fail on win env

### LINKED ISSUE #402: Failed to build on Windows. 'rm' is not recognized as an internal or external command
This is pretty easy to fix:
`rm -rf -> rimraf` in all `package.json`, i'll create PR for these.

* **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What modules are related to this pull-request**
- [x] express-engine
- [x] grunt-prerender
- [x] gulp-prerender
- [x] hapi-engine
- [ ] preboot
- [ ] universal-preview
- [x] angular2-universal-polyfills
- [x] universal
- [x] webpack-prerender

* **Do you want to request a *feature* or report a *bug*?**

bug

* **What is the current behavior?**

I'm trying to build on Windows and it fails.

Error:

`'rm' is not recognized as an internal or external command`

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

Run npm i in some of selected above modules under win enviroment.

* **What is the expected behavior?**

Npm installed successfully

* **What is the motivation / use case for changing the behavior?**

I'm one of this strange guys who love both - angular and aspnet, so i have to sit on win environment.

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all ]
- Language: [all]
- OS:  [Windows]
- Platform: [.Net]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

### PR DESCRIPTION
**Pull request by laskoviymishka**
Closes #402 
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/universal/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What modules are related to this pull-request**
- [x] express-engine
- [x] grunt-prerender
- [x] gulp-prerender
- [x] hapi-engine
- [ ] preboot
- [ ] universal-preview
- [x] angular2-universal-polyfills
- [x] universal
- [x] webpack-prerender

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
 change rm -rf to rimraf to prevent npm install fail on win env

* **What is the current behavior?** (You can also link to an open issue here)
See issue #402 

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Other information**:

### CODE REVIEW

**Comment by gdi2290** [comment]
thanks!

**Comment by MarkPieszak** [comment]
What version of windows do you have @laskoviymishka I'm on windows 7 and it just won't build, the `rm -rf` were one issue, but NPM keeps throwing ERRLIFECYCLE because of typings, and stops the whole install process.  If you're on windows 7 can you try an `npm run install:all` from the root of the project?

**Comment by laskoviymishka** [comment]
@MarkPieszak i use win10. What version of node are you using?

**Comment by MarkPieszak** [comment]
The latest, I've tried to get in touch with `npm` people but with no luck... When running `tsc` in command line and getting a few "minor" errors (that tsc usually throws), in Windows 7 during a big loop of installs / post installs etc, NPM errors out completely in Win7 because of this. Doesn't look like they're going to fix it though hah. @laskoviymishka

**Comment by laskoviymishka** [comment]
Well @MarkPieszak, angular hate this strange guys who sit on win. I still wasn't able to build angular2 main repo on my workstation. You may try some virtual machine, may be somewhere there can be found a vagrant image. I still have no luck with this.

**Pull request merged**
