### PR TITLE
fix(node-renderer): remove unused proxy imports from some test files

### PR DESCRIPTION
**Pull request by LendsMan**
- **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/universal/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- **What modules are related to this pull-request**
- [ ] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [ ] hapi-engine
- [ ] universal-next
- [ ] universal
- [ ] webpack-prerender
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
  remove unused proxy imports from some test files
- **What is the current behavior?** (You can also link to an open issue here)
- **What is the new behavior (if this is a feature change)?**
- **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
  No
- **Other information**:

Fast fix for #597. It seems like this part of code brakes styles for other routes.
https://github.com/angular/universal/issues/597

### CODE REVIEW

**Comment by gdi2290** [comment]
thanks, I edited your PR a bit

**Comment by gdi2290** [comment]
for workaround see universal-starter https://github.com/angular/universal-starter/commit/03105393fdc22fc055583258f0ca04afb59ec6d1

**Comment by LendsMan** [comment]
Thanks. How can I pass CLA test?

@gdi2290 have you seen this one? https://github.com/angular/angular/pull/12350/files
It fixed angular universal's style problem for me without removing isBlank check.

**Comment by gdi2290** [comment]
will be fixed in ng4 
https://github.com/angular/angular/issues/13822

**Pull request closed without merging**
