### PR TITLE
FIX: Change path to preboot_node

### PR DESCRIPTION
**Pull request by jamsea**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/universal/blob/master/CONTRIBUTING.md#commit-message-format
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What modules are related to this pull-request**
- [x] preboot

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bug fix

* **What is the current behavior?** (You can also link to an open issue here)
When using preboot currently in another project, an error is thrown because dist/preboot_node.js is trying to include another commonjs module from a different file path.

* **What is the new behavior (if this is a feature change)?**
An error is no longer thrown, and preboot node works now.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Other information**:

### CODE REVIEW

**Comment by goldibex** [comment]
any movement on this? it's blocking me as well.

**Comment by MarkPieszak** [comment]
LTGM @gdi2290

**Comment by goldibex** [comment]
guys, we're still waiting on this two weeks later. is there an update as to when it might be merged?

**Comment by MarkPieszak** [comment]
@jeffwhelpley I think you just recently changed this in the actual preboot repo right?
@goldibex Preboot has moved, it's actually not part of this repo anymore.

**Comment by gdi2290** [comment]
closing for now since preboot moved

**Pull request closed without merging**
