### PR TITLE
chore: server module source

### LINKED ISSUE #3: Merge content for serverside rendering as a single commit

### PR DESCRIPTION
**Pull request by gdi2290**
closes #3

I'm missing examples atm

[Review on Reviewable](https://reviewable.io/reviews/angular/universal/6)

### CODE REVIEW

**Comment by tbosch** [comment]
Shouldn't we ignore `dev_modules/` in `.gitignore` as well?

**Comment by gdi2290** [comment]
`dev_modules` was our hack folder to fix `rtts_assert` but I can try again to see if we still have the same problem. I can also move `traceur-runtime` into npm or require the one in angular. I'll see if we can remove `dev_modules`

**Comment by tbosch** [comment]
Yes, please do. `rtts_assert` should not be used by angular any more...

**Comment by gdi2290** [comment]
@tbosch `rtts_assert` was removed and I also have the debug and todo app working in examples.
right now the folder structure for examples is weird

```
modules/
   examples/
     app/
       client/
         app.js * browser bootstrap and bindings
       public/
       server/
         ...   *  node app including server render and bindings
       universal/   * our universal code that works both on client and server
         app/  * our debug app
         todo/ * our todo app
index.js * our source for starting our example node server
```
I probably should remove promote the folders include on `modules/examples/app` then remove `modules/examples/app`

**Comment by tbosch** [comment]
Ping? Please merge!

**Pull request merged**
