### PR TITLE
refactor(universal): --noImplicitAny support

### PR DESCRIPTION
**Pull request by vvakame**
* **Please check if the PR fulfills these requirements**
- [X] The commit message follows our guidelines: https://github.com/angular/universal/blob/master/CONTRIBUTING.md#commit-message-format
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

* **What modules are related to this pull-request**
- [ ] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [ ] hapi-engine
- [ ] universal-next
- [X] universal
- [ ] webpack-prerender

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

improve ts files.
Now, angular2-platform-node (and preboot) are not compatible with --noImplicitAny options.
This is spread affect to user land tsconfig settings.
I want to use --noImplicitAny options in my project.

* **What is the current behavior?** (You can also link to an open issue here)

Users can't use --noImplicitAny with this package.

* **What is the new behavior (if this is a feature change)?**

We can use --noImplicitAny with this package!

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

maybe no

* **Other information**:

https://github.com/angular/preboot/pull/23

### CODE REVIEW

**Comment by vvakame** [comment]
try to use `noImplicitAny: true`, but preboot is not support --noImplicitAny.
we got following errors.

```
node_modules/preboot/preboot.d.ts(53,5): error TS7010: 'preventDefault', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/preboot/preboot.d.ts(94,5): error TS7010: 'addEventListener', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/preboot/preboot.d.ts(125,5): error TS7010: 'setSelectionRange', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/preboot/preboot.d.ts(132,5): error TS7010: 'remove', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/preboot/preboot.d.ts(133,5): error TS7010: 'focus', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/preboot/preboot.d.ts(134,5): error TS7010: 'dispatchEvent', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/preboot/preboot.d.ts(137,5): error TS7010: 'insertBefore', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/preboot/preboot.d.ts(138,5): error TS7010: 'addEventListener', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/preboot/preboot.d.ts(139,5): error TS7010: 'removeEventListener', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/preboot/preboot.d.ts(142,5): error TS7010: 'appendChild', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/preboot/preboot.d.ts(143,5): error TS7010: 'setAttribute', which lacks return-type annotation, implicitly has an 'any' return type.
```

**Comment by gdi2290** [comment]
LGTM

**Comment by gdi2290** [comment]
@vvakame can you update to latest?

**Comment by vvakame** [comment]
@gdi2290 done! Is it OK?

**Comment by gdi2290** [comment]
thanks!

**Pull request merged**
