### PR TITLE
Localized routes in routefile.txt

### LINKED ISSUE #1893: i18n multilingual routes - @nguniversal/builders:prerender
My app is using multilingual routes. The route definition in the app.module.ts is looking like the following:
 
`{ path: $localize`:@@app.routes.menu:menu`, component: MenuComponent, pathMatch: 'full' }`

Since the ivy update this is working fine.

It would be useful to be able to prerender different routes per language. My angular.json prerender definition is looking like: 

```
"prerender": {
          "builder": "@nguniversal/builders:prerender",
          "options": {
            "browserTarget": "app:build:production",
            "serverTarget": "app:server:production",
            "routesFile": "./routes.txt"
          }
}
```

It is not possible to prerender different routes per locale.

A solution would be to use the $localize`:@@app.routes.menu:menu` syntax in the routeFile or to add a routeFile per locale.

### PR DESCRIPTION
**Pull request by muehle28**
With this changes it is possible to add localized routes to the routefile

routes.txt

/en/
/en/site1
/de/
/de/seite1
/it/
/it/sito1
/routeforalllanguages

If the language path is equal the localeDirectory the route is just used for that localized build. If the language path is missing or does not correspond with a localeDirectory the route is used for every build (normal behaviour).

Fixes #1893

### CODE REVIEW

**Comment by muehle28** [comment]
@googlebot I signed it!

**Comment by muehle28** [comment]
@googlebot I fixed it

**Comment by hiepxanh** [comment]
@muehle28 can you update your commit message? it not valid lint on circle CI

**Comment by alan-agius4** [comment]
Thanks for your contribution but this PR does not apply cleanly.

**Pull request closed without merging**
