### PR TITLE
fix(express-engine): adds deps to compilerFactory

### LINKED ISSUE #774: bug(express-engine): server fails with new StaticInjector
* **I'm submitting a ...**
```
- [x] bug report
- [ ] feature request
```

* **What modules are related to this Issue?**
```
- [ ] aspnetcore-engine
- [x] express-engine
- [ ] hapi-engine
```

* **What is the current behavior?**

express-engine fails to start due to problems with the new StaticInjector in Angular v5.0.0

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

1. Create new universal project
2. Upgrade deps to Angular v5.0.0-beta.3
3. Try to run a server using express-engine

* **What is the expected behavior?**

express-engine should load dependencies using the new StaticInjector pattern introduced in Angular v5.0.0

* **What is the motivation / use case for changing the behavior?**

express-engine is unusable without these changes in the newest release of Angular

* **Please tell us about your environment:**

- Angular version: 5.0.0-beta.3
- Browser: [**all** | Chrome XX | Firefox XX | IE XX | Safari XX ]
- Language: [**all** | TypeScript X.X | ES6/7 | ES5 ]
- OS:  [**all** | Mac OS X | Windows | Linux ]
- Platform: [**all** | NodeJs | Java | PHP | .NETCore | Ruby]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

```
/home/debian/angular2/package/node_modules/@angular/core/bundles/core.umd.js:1598
        throw staticError('\'deps\' required', provider);
        ^

Error: StaticInjectorError[{provide:ResourceLoader, useClass:FileLoader}]: 'deps' required
    at staticError (/home/debian/angular2/package/node_modules/@angular/core/bundles/core.umd.js:1631:12)
    at computeDeps (/home/debian/angular2/package/node_modules/@angular/core/bundles/core.umd.js:1598:15)
    at resolveProvider (/home/debian/angular2/package/node_modules/@angular/core/bundles/core.umd.js:1389:33)
    at recursivelyProcessProviders (/home/debian/angular2/package/node_modules/@angular/core/bundles/core.umd.js:1446:53)
    at recursivelyProcessProviders (/home/debian/angular2/package/node_modules/@angular/core/bundles/core.umd.js:1435:17)
    at recursivelyProcessProviders (/home/debian/angular2/package/node_modules/@angular/core/bundles/core.umd.js:1435:17)
    at new StaticInjector (/home/debian/angular2/package/node_modules/@angular/core/bundles/core.umd.js:1354:9)
    at Function.Injector.create (/home/debian/angular2/package/node_modules/@angular/core/bundles/core.umd.js:1323:16)
    at JitCompilerFactory.createCompiler (/home/debian/angular2/package/node_modules/@angular/compiler/bundles/compiler.umd.js:27754:64)
    at Object.ngExpressEngine (/home/debian/angular2/package/node_modules/@nguniversal/express-engine/src/main.js:22:36)
```

### PR DESCRIPTION
**Pull request by CaerusKaru**
- Adds compatibility with latest version of Angular (v5.0.0-beta.3)
- Fixes #774

* **Please check if the PR fulfills these requirements**
```
- [x] The commit message follows our guidelines: https://github.com/angular/universal/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
```

* **What modules are related to this pull-request**
```
- [ ] aspnetcore-engine
- [x] express-engine
- [ ] hapi-engine
```

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Bug fix

* **What is the current behavior?** (You can also link to an open issue here)

#774 

* **What is the new behavior (if this is a feature change)?**

Adds compatibility with latest version of Angular (v5.0.0-beta.3)

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

No

### CODE REVIEW

**Comment by Owain94** [comment]
Line 16 probably has to be changed from `providers?: Provider[];` to `providers?: StaticProvider[];` otherwise the `extraProviders ` on line 80 will still be of type `Provider[]`

**Comment by CaerusKaru** [comment]
@Owain94 You're probably right, but that seems out of scope for this PR. This fix is just a patch to ensure compatibility with Angular v5, which the single line change fixes.

**Comment by vikerman** [comment]
Hi - I don't understand the issue and why putting the deps fixes it. I didn't realize useClass takes in a deps field.

**Comment by Owain94** [comment]
@vikerman Angular 5 switched to the StaticInjector instead of the ReflectiveInjector. This is to satisfy the StaticInjector.

https://github.com/angular/angular/commit/fcadbf4bf6d00ea5b250a8069e05b3e4bd000a29

**Comment by vikerman** [comment]
Sorry - this is taking longer. Have to decide a versioning/branching scheme. Probably will create 2.x branch/release compatible with Angular 5.

**Comment by Toxicable** [comment]
@vikerman Is there a docs or proposal somewhere that we could help out on to make the versioning scheme / direction forwards for this repo? Or maybe shall I draft one up if that helps?

**Comment by patrickmichalina** [comment]
When will this get integrated?

**Comment by CaerusKaru** [comment]
@vikerman If you want, I can resubmit this PR to a different branch. In the meantime, I've synced this back up with master.

**Comment by Toxicable** [comment]
@CaerusKaru no need to make a new PR, although you do need to squash your commits down to just one

**Comment by CaerusKaru** [comment]
@Toxicable Done

**Comment by vikerman** [comment]
Folded into https://github.com/angular/universal/commit/5c705cb51362bd448c0b8ac293da867a3a1913f4

**Pull request closed without merging**
