### PR TITLE
chore(server-patch): rename server-patch.ts to universal-polyfill.ts …

### PR DESCRIPTION
**Pull request by manekinekko**
chore(server-patch): rename server-patch.ts to universal-polyfill.ts …

### CODE REVIEW

**Comment by gdi2290** [comment]
I need this now, so I'm going to see if I can merge it

**Comment by gdi2290** [comment]
I'm going to close this for later when we should refactor into another module

**Comment by manekinekko** [comment]
I'll leave the branch open

**Comment by manekinekko** [comment]
@gdi2290  Does this one still need reworking?

**Pull request closed without merging**
