### PR TITLE
docs(express, hapi): fix token import example

### PR DESCRIPTION
**Pull request by jdpnielsen**
```
- [x] The commit message follows [our guidelines](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#commit-message-format)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
```

* **What modules are related to this pull-request**
```
- [ ] aspnetcore-engine
- [ ] common
- [x] express-engine
- [x] hapi-engine
- [ ] module-map-ngfactory-loader
```

* **What kind of change does this PR introduce?**
Docs update

* **What is the current behavior?**
See https://github.com/angular/universal/issues/918

### CODE REVIEW

**Comment by CaerusKaru** [comment]
@jdpnielsen Thanks for this patch! This might also constitute a breaking change notice in the CHANGELOG. If you want, you can add a PR for that too, o/w I'll add one later today.

**Comment by thorgotothegym** [comment]
Pues ya Bípedo la 110010
0Gracias no12k dopado j itsuppppp

**Comment by thorgotothegym** [comment]
Pues 1 y

**Comment by jdpnielsen** [comment]
@CaerusKaru I'm not sure how you want it worded/formatted for the changelog - i won't mind if you just go ahead and add it. 
Thanks for merging this so quickly. Hopefully it will save other devs some time/pain.

**Pull request merged**
