### PR TITLE
fix(node-platform): provide ResourceLoader for Templates that aren't inlined

### PR DESCRIPTION
**Pull request by jkuri**
- [ ] add simple test for that fix

This adds fix that templates does not have to be inlined.
This PR still need discussion if it's available to use this without `moduleId: module.id` option to get relative paths to templates. After chatting with Patrick there might be an option to let AoT compiler inline all templates.

\cc @gdi2290

### CODE REVIEW

**Comment by gdi2290** [comment]
AoT should be inlining the templates if it's not already. This is to solve for the case where you might be using SystemJS or something without inlining these resources

**Comment by gdi2290** [comment]
can you update the branch to latest again.

**Comment by jkuri** [comment]
@gdi2290 rebased.

**Comment by demurgos** [comment]
Could you publish the version with the fix to npm ?

**Pull request merged**
