### PR TITLE
Angular2 Alpha-0.46

### PR DESCRIPTION
**Pull request by mikeallisonJS**
Alpha 0.46 support
Better angular core type support
Less compiler warnings

### CODE REVIEW

**Comment by gdi2290** [comment]
I want to merge this but you repo has a different history from this one.

**Comment by mikeallisonJS** [comment]
Just curious, what about the history is incorrect? I know I pulled in work from @SteveSanderson & @jeffwhelpley , but other than that it's pretty much the base + the gulp version of the shell build.

**Comment by jeffwhelpley** [comment]
@mikeallisonJS sorry for the lack of communication on this one. We are going to pick up steam on a number of changes the next couple weeks and we want to get this merged. I think @gdi2290 wanted you clean up the history so that you just have one change set on top of the latest. I am don't have the git skills to advise on this, but I think Patrick and work with you to get it fixed if you have time.

**Comment by mikeallisonJS** [comment]
Gotcha, I'll see what I can do. I'm getting close on .47 as well.... although it's a much heftier change than the previous releases.

**Comment by jeffwhelpley** [comment]
That's awesome, man. Thanks for the work. We really appreciate it. @gdi2290 will reach out to you shortly.

**Comment by gdi2290** [comment]
@mikeallisonJS let's pair on it. Are you free tomorrow

**Comment by mikeallisonJS** [comment]
@gdi2290 I should be, feel free to add me on skype or gtalk (mikeallison1 / dj.mikeallison@gmail.com)

**Comment by gdi2290** [comment]
merged via https://github.com/angular/universal/commit/2be67aa3553ad912f5d036cf0d335986955c0abc from https://github.com/angular/universal/pull/148

**Pull request closed without merging**
