### PR TITLE
bug(platform-node): Throw error to parent catch of serializeModule

### PR DESCRIPTION
**Pull request by MarkPieszak**
Helps pass errors to `.catch()` of `Zone.run( ... serializeModule() )`

#550

### CODE REVIEW

**Comment by gdi2290** [comment]
did you test that this works?

**Comment by gdi2290** [comment]
I would think the error catching have to be in asyncPromiseSeries

**Comment by MarkPieszak** [comment]
It seemed to work with random errors I tried throwing but should look into it more. In a wedding today so can't but could try it out more tomorrow! 

Isn't there already a catcher in the async series that would bubble up?

**Comment by gdi2290** [comment]
@MarkPieszak any updates on this?

**Comment by MarkPieszak** [comment]
@gdi2290 We should be all set (for now) with this at least from this end. It passes any errors thrown up to the caller.

**Comment by gdi2290** [comment]
LGTM

**Comment by gdi2290** [comment]
this is needed for asp.net

**Pull request merged**
